/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Sara
 */
public class RegistroUsuarios extends javax.swing.JFrame {

    String user;

    /**
     * Creates new form RegistroUsuarios
     */
    public RegistroUsuarios() {
        initComponents();
        user = Login.user;
        this.setTitle("REGISTRAR USUARIO  -SESION DE " + user);
        this.setSize(673, 630);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

//inicio agregar y escalar la inm del label 
        ImageIcon fondo = new ImageIcon("src/img/17538.jpg");
        Icon icono_fondo = new ImageIcon(fondo.getImage().getScaledInstance(jlabel_fondo.getWidth(),
                jlabel_fondo.getHeight(), Image.SCALE_DEFAULT));

        jlabel_fondo.setIcon(icono_fondo);
        this.repaint();
// fin de fondo de icono
    }
// icono en cabezera jframe e icono de la app

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/user1.png"));
        return retValue;
    }
//fin icono jframeFrame

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        cmb_clasificacion = new javax.swing.JComboBox<>();
        btn_guardarReg = new javax.swing.JButton();
        jlabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de usuarios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 260, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 260, -1));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 260, -1));

        txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 260, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Usuario: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Telefono: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Clasificaion de Empleado: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Nombre: ");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Correo: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 70, 70));

        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 260, -1));

        cmb_clasificacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmb_clasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Capturista", "Tecnico", "Administrador" }));
        cmb_clasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_clasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 200, -1));

        btn_guardarReg.setBackground(new java.awt.Color(255, 255, 255));
        btn_guardarReg.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_guardarReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar-usuario.png"))); // NOI18N
        btn_guardarReg.setText("Agregar");
        btn_guardarReg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(58, 134, 255), new java.awt.Color(58, 134, 255), new java.awt.Color(58, 134, 255), new java.awt.Color(58, 134, 255)));
        btn_guardarReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarRegActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardarReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 100, 40));

        jlabel_fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoActionPerformed

    private void cmb_clasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_clasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_clasificacionActionPerformed

    private void btn_guardarRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarRegActionPerformed
        // TODO add your handling code here:
        int permisos_cmb, validacion = 0;
        String Nombre, correo, telefono, username, pass, permisos_str;

//traer el texto que tienen el usuario inserto en los txt
        Nombre = txt_nombre.getText().trim();
        correo = txt_email.getText().trim(); //trim sirve para eliminar los espacios que se encuntre n al principio o final del texto
        telefono = txt_telefono.getText().trim();
        username = txt_username.getText().trim();
        pass = txt_password.getText().trim();
        permisos_cmb = cmb_clasificacion.getSelectedIndex() + 1;

//validar que los campos tengas texto
        if (correo.equals(""))//verifique que no este vacio el campo
        {
            txt_email.setBackground(Color.red);
JOptionPane.showMessageDialog(null, "EL CAMPO DE CORREO ESTA VACIO");
            validacion++;
        }
        if (Nombre.equals(""))//verifique que no este vacio el campo
        {
            txt_nombre.setBackground(Color.red);
            validacion++;
        }
        if (telefono.equals(""))//verifique que no este vacio el campo
        {
            txt_telefono.setBackground(Color.red);
            validacion++;
        }
        if (username.equals(""))//verifique que no este vacio el campo
        {
            txt_username.setBackground(Color.red);
            validacion++;
        }
        if (pass.equals(""))//verifique que no este vacio el campo
        {
            txt_password.setBackground(Color.red);
            validacion++;
        }
//fin de la validacion de los campos 
/// para la seleccion decombox y guardar en bd
        if (permisos_cmb == 2)//verifique que no este vacio el campo
        {
            permisos_str = "Capturista";

        } else if (permisos_cmb == 3) {
            permisos_str = "Tecnico";
        } else if (permisos_cmb == 4) {
            permisos_str = "Administrador";
        }
        try {
            Connection cn3 = Conexion.conectar();
            PreparedStatement pst = cn3.prepareStatement("select username from usuarios where username = '" + username + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_username.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "EL username ya extiste,elige otro.");
                cn3.close();
            } else {
}
        } catch (SQLException e) {
            System.err.println("ERROR AL VALIDAR NOMBRE DE USUARIO" + e);

        }
    }//GEN-LAST:event_btn_guardarRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarReg;
    private javax.swing.JComboBox<String> cmb_clasificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlabel_fondo;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
